CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    email varchar(50) NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL,
    description varchar(500) NOT NULL,
    available boolean NOT NULL,
    owner_id bigint REFERENCES users(id) NOT NULL ON DELETE CASCADE,
    request_id bigint REFERENCES requests(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date timestamp NOT NULL,
    end_date timestamp NOT NULL,
    item_id bigint REFERENCES items(id) NOT NULL ON DELETE CASCADE,
    booker_id bigint REFERENCES users(id) NOT NULL ON DELETE CASCADE,
    status varchar(20) NOT NULL
);
CREATE TABLE IF NOT EXISTS comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id bigint REFERENCES items(id) NOT NULL ON DELETE CASCADE,
    author_id bigint REFERENCES users(id) NOT NULL ON DELETE CASCADE,
    text varchar(500) NOT NULL,
    created timestamp NOT NULL
);
CREATE TABLE IF NOT EXISTS requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description varchar(500) NOT NULL,
    created timestamp NOT NULL,
    author_id bigint REFERENCES users(id) NOT NULL ON DELETE CASCADE
);